### ISSUE TITLE
how to make this work in node.js and react?

### ISSUE THREAD

**Issue by Ethan-Dolan** [crypto-su/corsDown#1]
I am trying to pull this off through react. so when a instagram link is generated through api i want to directly display it. how to make your code work on react

**Comment by Mrjavaci** [comment]
Actually, you don't have to do anything for the code to work on React.
All you need to do on React is to implement this js code on the ui side.

If you want to rewrite the code specifically for react, contact us. Let's do.

**Comment by Ethan-Dolan** [comment]
I am trying to do it for a month.
Can you please elaborate exactly how can it be done.
Thank you

**Comment by Ethan-Dolan** [comment]
> Actually, you don't have to do anything for the code to work on React. All you need to do on React is to implement this js code on the ui side.
> 
> If you want to rewrite the code specifically for react, contact us. Let's do.

How do i contact you your website is not working?
Please guide me to the solution

**Comment by Mrjavaci** [comment]
> > Actually, you don't have to do anything for the code to work on React. All you need to do on React is to implement this js code on the ui side.
> > If you want to rewrite the code specifically for react, contact us. Let's do.
> 
> How do i contact you your website is not working? Please guide me to the solution

There is currently no situation that requires you to contact us.
I will edit the relevant code for React and nodejs and leave the URL here.

**Comment by Ethan-Dolan** [comment]
> > > Actually, you don't have to do anything for the code to work on React. All you need to do on React is to implement this js code on the ui side.
> > > If you want to rewrite the code specifically for react, contact us. Let's do.
> > 
> > 
> > How do i contact you your website is not working? Please guide me to the solution
> 
> There is currently no situation that requires you to contact us. I will edit the relevant code for React and nodejs and leave the URL here.

Thank you very much. I am looking forward to it.

**Comment by Njima1572** [comment]
For nodejs / react, I've created a function in somewhere like this, 
``` typescript
const readImage = (url: string) => {
  const p = url.split("/");
  var t = '';
  for (let i = 0; i < p.length; i++) {
    if (i == 2) {
      t += p[i].replaceAll('-', '--').replaceAll('.', '-') + atob('LnRyYW5zbGF0ZS5nb29n') + '/';
    } else { if (i != p.length - 1) { t += p[i] + '/'; } else { t += p[i]; } }
  }
  return encodeURI(t);
}
```

Then used it like,

`<img src={readImage(target_url)} />`

This has worked for me.

BTW, thank you for your work! @crypto-su
